name: Build the scripts tarball
run-name: Building the scripts tarball
on: [push]
jobs:
  Build-Tarball:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Compress action step
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          files: |
            ./scripts
          outPath: scripts.tar.gz
